trigger:
  branches:
    include:
      - main

pool: david-pool

stages:

- stage: TerraformPlan
  displayName: Terraform Plan

  jobs:
  - job: Plan
    displayName: Terraform Init and Plan

    steps:

    - task: tfsec@1
      displayName: tfsec Security Scan
      inputs:
        version: 'v1.26.0'

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'infra-serviceconnection'
        backendAzureRmResourceGroupName: 'rg-david-prod'
        backendAzureRmStorageAccountName: 'davidstg91'
        backendAzureRmContainerName: 'prodcontainer'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'infra-serviceconnection'


- stage: TerraformApply
  displayName: Terraform Apply
  dependsOn: TerraformPlan
  condition: succeeded()

  jobs:
  - deployment: Apply
    displayName: Apply Terraform
    environment: prod

    strategy:
      runOnce:
        deploy:
          steps:

          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'infra-serviceconnection'
              backendAzureRmResourceGroupName: 'rg-david-prod'
              backendAzureRmStorageAccountName: 'davidstg91'
              backendAzureRmContainerName: 'prodcontainer'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            displayName: Terraform Apply
            inputs:
              
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'infra-serviceconnection'